dist: trusty
sudo: required
language: node_js
node_js:
  - "9"
  - "8"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
before_install:
  - npm install -g npm
  - cp config.sample.js config.js
cache:
  yarn: true
  directories:
    - node_modules
script:
  - "npm test"
notifications:
  irc: "chat.freenode.net#mrnodebot"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
