language: node_js
node_js:
  - "9"
  - "8"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - npm install -g npm
  - cp config.sample.js config.js
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
script:
  - "npm test"
notifications:
  irc: "chat.freenode.net#mrnodebot"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
